version: "{build}"
image: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  PATH: C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%
build_script:
- cmd: >-
    paket.exe restore
    
    CreateNugetPackage
test: off
artifacts:
- path: deploy/*.nupkg
  name: NuGet
deploy: off
